version: "3.8"

services:
  app:
    image: pakpannn/api-gateway
    container_name: api-gateway
    depends_on:
      - mysql
      - redis
    env_file: ./.env
    volumes:
      - ./certbot/conf:/cert
      - ./certbot/www:/cert
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    networks:
      - dev

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - app
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - dev

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redis_data:/data
    networks:
      - dev

networks:
  dev:
    external: true

volumes:
  mysql_data:
  redis_data:
